export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
export const SENDING_REQUEST = 'SENDING_REQUEST';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const REFRESH_TOKEN_REQUEST = 'REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILURE = 'REFRESH_TOKEN_FAILURE';

export const RESTORE_TOKENS_REQUEST = 'RESTORE_TOKENS_REQUEST';
export const RESTORE_TOKENS_SUCCESS = 'RESTORE_TOKENS_SUCCESS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const REQUEST_ERROR = 'REQUEST_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';

export const GET_FOLDER_REQUEST = 'GET_FOLDER_REQUEST';
export const GET_FOLDER_SUCCESS = 'GET_FOLDER_SUCCESS';
export const GET_FOLDER_FAILURE = 'GET_FOLDER_FAILURE';

export const CREATE_FOLDER_REQUEST = 'CREATE_FOLDER_REQUEST';
export const CREATE_FOLDER_SUCCESS = 'CREATE_FOLDER_SUCCESS';
export const CREATE_FOLDER_FAILURE = 'CREATE_FOLDER_FAILURE';

export const CREATE_FILE_REQUEST = 'CREATE_FILE_REQUEST';
export const CREATE_FILE_SUCCESS = 'CREATE_FILE_SUCCESS';
export const CREATE_FILE_FAILURE = 'CREATE_FILE_FAILURE';

export const DELETE_SELECTED_ITEMS_SUCCESS = 'DELETE_SELECTED_ITEMS_SUCCESS';
export const DELETE_SELECTED_ITEMS_REQUEST = 'DELETE_SELECTED_ITEMS_REQUEST';
export const DELETE_SELECTED_ITEMS_FAILURE = 'DELETE_SELECTED_ITEMS_FAILURE';

export const SEARCH_ITEMS_REQUEST = 'SEARCH_ITEMS_REQUEST';
export const SEARCH_ITEMS_SUCCESS = 'SEARCH_ITEMS_SUCCESS';
export const SEARCH_ITEMS_FAILURE = 'SEARCH_ITEMS_FAILURE';

export const TOGGLE_ITEM = 'TOGGLE_ITEM';
export const TOGGLE_ALL_ITEMS = 'TOGGLE_ALL_ITEMS';

export const SORT_ITEMS = 'SORT_ITEMS';
export const CHANGE_VIEW = 'CHANGE_VIEW';
