export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
export const SENDING_REQUEST = 'SENDING_REQUEST';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const GET_FOLDER_REQUEST = 'GET_FOLDER_REQUEST';
export const GET_FOLDER_SUCCESS = 'GET_FOLDER_SUCCESS';

export const CREATE_FOLDER_REQUEST = 'CREATE_FOLDER_REQUEST';
export const CREATE_FOLDER_SUCCESS = 'CREATE_FOLDER_SUCCESS';

export const CREATE_FILE_REQUEST = 'CREATE_FILE_REQUEST';
export const CREATE_FILE_SUCCESS = 'CREATE_FILE_SUCCESS';

export const DELETE_SELECTED_ITEMS_SUCCESS = 'DELETE_SELECTED_ITEMS_SUCCESS';
export const DELETE_SELECTED_ITEMS_REQUEST = 'DELETE_SELECTED_ITEMS_REQUEST';

export const SEARCH_ITEMS_REQUEST = 'SEARCH_ITEMS_REQUEST';
export const SEARCH_ITEMS_SUCCESS = 'SEARCH_ITEMS_SUCCESS';

export const TOGGLE_ITEM = 'TOGGLE_ITEM';
export const TOGGLE_ALL_ITEMS = 'TOGGLE_ALL_ITEMS';

export const SORT_ITEMS = 'SORT_ITEMS';
export const CHANGE_VIEW = 'CHANGE_VIEW';
