export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
export const SENDING_REQUEST = 'SENDING_REQUEST';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const REFRESH_TOKEN_REQUEST = 'REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILURE = 'REFRESH_TOKEN_FAILURE';

export const RESTORE_TOKENS_REQUEST = 'RESTORE_TOKENS_REQUEST';
export const RESTORE_TOKENS_SUCCESS = 'RESTORE_TOKENS_SUCCESS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const REQUEST_ERROR = 'REQUEST_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';

export const GET_FOLDER_REQUEST = 'GET_FOLDER_REQUEST';
export const GET_FOLDER_SUCCESS = 'GET_FOLDER_SUCCESS';
export const GET_FOLDER_FAILURE = 'GET_FOLDER_FAILURE';

export const CREATE_FOLDER_REQUEST = 'CREATE_FOLDER_REQUEST';
export const CREATE_FOLDER_SUCCESS = 'CREATE_FOLDER_SUCCESS';
export const CREATE_FOLDER_FAILURE = 'CREATE_FOLDER_FAILURE';

export const CREATE_FILE_REQUEST = 'CREATE_FILE_REQUEST';
export const CREATE_FILE_SUCCESS = 'CREATE_FILE_SUCCESS';
export const CREATE_FILE_FAILURE = 'CREATE_FILE_FAILURE';

export const DELETE_SELECTED_ITEMS_SUCCESS = 'DELETE_SELECTED_ITEMS_SUCCESS';
export const DELETE_SELECTED_ITEMS_REQUEST = 'DELETE_SELECTED_ITEMS_REQUEST';
export const DELETE_SELECTED_ITEMS_FAILURE = 'DELETE_SELECTED_ITEMS_FAILURE';

export const SEARCH_ITEMS_REQUEST = 'SEARCH_ITEMS_REQUEST';
export const SEARCH_ITEMS_SUCCESS = 'SEARCH_ITEMS_SUCCESS';
export const SEARCH_ITEMS_FAILURE = 'SEARCH_ITEMS_FAILURE';

export const TOGGLE_ITEM = 'TOGGLE_ITEM';
export const TOGGLE_ALL_ITEMS = 'TOGGLE_ALL_ITEMS';

export const TOGGLE_ITEM_RENAME = 'TOGGLE_ITEM_RENAME';

export const TOGGLE_TAGS_EDIT = 'TOGGLE_TAGS_EDIT';

export const RENAME_ITEM_REQUEST = 'RENAME_ITEM_REQUEST';
export const RENAME_ITEM_SUCCESS = 'RENAME_ITEM_SUCCESS';
export const RENAME_ITEM_FAILURE = 'RENAME_ITEM_FAILURE';

export const ADD_TAG_REQUEST = 'ADD_TAG_REQUEST';
export const ADD_TAG_SUCCESS = 'ADD_TAG_SUCCESS';
export const ADD_TAG_FAILURE = 'ADD_TAG_FAILURE';

export const DELETE_TAG_REQUEST = 'DELETE_TAG_REQUEST';
export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS';
export const DELETE_TAG_FAILURE = 'DELETE_TAG_FAILURE';

export const SEARCH_TAGS_REQUEST = 'SEARCH_TAGS_REQUEST';
export const SEARCH_TAGS_SUCCESS = 'SEARCH_TAGS_SUCCESS';
export const SEARCH_TAGS_FAILURE = 'SEARCH_TAGS_FAILURE';

export const GET_FILES_URLS_SUCCESS = 'GET_FILES_URLS_SUCCESS';
export const DOWNLOAD_FILE = 'DOWNLOAD_FILE';

export const ADD_FILTER_TAG = 'ADD_FILTER_TAG';
export const DELETE_FILTER_TAG = 'DELETE_FILTER_TAG';

export const SORT_ITEMS = 'SORT_ITEMS';
export const CHANGE_VIEW = 'CHANGE_VIEW';

export const FILTER_ITEMS_BY_TAGS_REQUEST = 'FILTER_ITEMS_BY_TAGS_REQUEST';
export const FILTER_ITEMS_BY_TAGS_SUCCESS = 'FILTER_ITEMS_BY_TAGS_SUCCESS';
export const FILTER_ITEMS_BY_TAGS_FAILURE = 'FILTER_ITEMS_BY_TAGS_FAILURE';
